### PR TITLE
chore!: make the repo ESM first

### PR DESCRIPTION
**Pull request by wojtekmaj**
## What is the motivation for this pull request?

Unblocks #670

Marks the repository as ESM first and migrates tests to ESM.

The main reason for that is #670. ESM import paths are perfectly compatible with CJS (so: compiling code down to CJS should work if you're not using e.g. top-level await), but the same can't be told the other way around. So, in order to have proper ESM/CJS compat, the repository HAS TO be ESM-first.

Relates to #669

## What is the current behavior?

Repository CJS-first.
Tests ran in CommonJS.

## What is the new behavior?

Repository ESM-first.
Tests ran in ESM

## Checklist:

- [ ] [Conventional Commits](https://www.conventionalcommits.org/)
- [ ] Tests
- [ ] Types
- [ ] Documentation

### CODE REVIEW

**Review by remarkablemark — COMMENTED** [review]
@wojtekmaj I appreciate you taking the time to refactor this codebase to ESM. However, I'm a bit hesitant to merge this since it's a breaking change. Does the fix in your original issue https://github.com/remarkablemark/html-react-parser/issues/1305 work for you?

**Comment by wojtekmaj** [comment]
Hi @remarkablemark - I didn't expect you to merge this PR right away. But I do hope it'd be a starting point if you ever want to do an ESM migration.

The sole reason for "making the repo ESM first" (which all comes down to `type: "module"` and how .js extension is treated by default) is that the testing suite you're using is incapable of CJS/ESM interop. Should you decide to switch html-dom-parser and html-react-parser to e.g. Vitest, I could easily make it "ESM first" (with 100% ESM support) without any breaking changes. How that sounds?

**Comment by remarkablemark** [comment]
@wojtekmaj I'm open to refactoring the tests from Mocha to Jest to be consistent with `html-react-parser`. In regards to making this repo ESM first, I'd like to maintain backwards compatibility for a bit longer before making the breaking change

**Comment by wojtekmaj** [comment]
I may have been unclear. We can keep CJS and we can have no breaking changes, all while providing good ESM support, but Mocha is blocking us from doing so. Jest is no better, actually, it's notably bad with ESM.

**Comment by remarkablemark** [comment]
Gotcha, as long as the unit and E2E tests still run and pass, I'm good with changing the test framework

**Pull request closed without merging**
