### PR TITLE
feat: add compatibility for react-native

### PR DESCRIPTION
**Pull request by vTrip**
## What is the motivation for this pull request?

Package did not work on react-native

## What is the current behavior?

react-native was using the client library which threw error in reference `document`

## What is the new behavior?

react-native uses the server library

### CODE REVIEW

**Review by remarkablemark — COMMENTED** [review]
Thanks for opening the PR @vTrip. We use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) to help with automated releases, so do you mind amending your commit message so it passes lint?

```sh
git commit --amend -m "feat: add compatibility for react-native"
git push -f
```

Also, can you rebase with `master` since I fixed a test failure

**Comment by vTrip** [comment]
> Thanks for opening the PR @vTrip. We use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) to help with automated releases, so do you mind amending your commit message so it passes lint?
> 
> ```shell
> git commit --amend -m "feat: add compatibility for react-native"
> git push -f
> ```
> 
> Also, can you rebase with `master` since I fixed a test failure

thanks! Let me know if I've done that correct

Cheers

**Review by remarkablemark — APPROVED** [review]
LGTM!

**Comment by remarkablemark** [comment]
Released in https://github.com/remarkablemark/html-dom-parser/pull/247#issuecomment-1099317474

**Comment by remarkablemark** [comment]
Released https://github.com/remarkablemark/html-react-parser/pull/513#issuecomment-1099833655

**Pull request merged**
